// src/components/PageFooter.svelte
<footer class="text-center">
  <div class="bg-dark">
    <div class="container">
      <div class="row">
        <a
          href="https://github.com/428lab"
          class="
              col
              bg-github
              d-block
              py-3
              d-flex
              align-items-end
              justify-content-center
            "
        >
          <img src="/blandlogo/github.svg" height="28px" />
          <span class="h4 ms-3 text-white mb-0 d-none d-md-flex">GitHub</span>
        </a>
        <a
          href="https://www.facebook.com/%E5%9B%9B%E8%B0%B7%E3%83%A9%E3%83%9C-102455797824507/"
          class="
              col
              bg-facebook
              d-block
              py-3
              d-flex
              align-items-end
              justify-content-center
            "
        >
          <img src="/blandlogo/facebook.svg" height="28px" />
          <span class="h4 ms-3 text-white mb-0 d-none d-md-flex">Facebook</span>
        </a>
        <a
          href="https://twitter.com/lab_428"
          class="
              col
              bg-twitter
              d-block
              py-3
              d-flex
              align-items-end
              justify-content-center
            "
        >
          <img src="/blandlogo/twitter.svg" height="28px" />
          <span class="h4 ms-3 text-white mb-0 d-none d-md-flex">Twitter</span>
        </a>
      </div>
    </div>
  </div>
  <p class="mt-5 mb-5">&copy; 2020 - 四谷ラボ</p>
</footer>

// src/components/Page-Footer.vue
<template>
  <footer class="text-center">
    <div class="bg-dark">
      <div class="container">
        <div class="row">
          <a
            href="https://github.com/428lab"
            class="
              col
              bg-github
              d-block
              py-3
              d-flex
              align-items-end
              justify-content-center
            "
          >
            <img src="/blandlogo/github.svg" height="28px" />
            <span class="h4 ml-3 text-white mb-0 d-none d-md-flex">GitHub</span>
          </a>
          <a
            href="https://www.facebook.com/%E5%9B%9B%E8%B0%B7%E3%83%A9%E3%83%9C-102455797824507/"
            class="
              col
              bg-facebook
              d-block
              py-3
              d-flex
              align-items-end
              justify-content-center
            "
          >
            <img src="/blandlogo/facebook.svg" height="28px" />
            <span class="h4 ml-3 text-white mb-0 d-none d-md-flex">Facebook</span>
          </a>
          <a
            href="https://twitter.com/lab_428"
            class="
              col
              bg-twitter
              d-block
              py-3
              d-flex
              align-items-end
              justify-content-center
            "
          >
            <img src="/blandlogo/twitter.svg" height="28px" />
            <span class="h4 ml-3 text-white mb-0 d-none d-md-flex">Twitter</span>
          </a>
        </div>
      </div>
    </div>
    <p class="mt-5 mb-5">&copy; 2020 - 四谷ラボ</p>
  </footer>
</template>
